services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_ADDR=redis:6379
      - secret=${secret}
volumes:
  mongo_data: